### ISSUE TITLE
Can't find .sketchplugin file

### ISSUE THREAD

**Issue by agoulet** [mathieudutour/sketch-remove-bg#1]
When I download the folder, it doesn't have the .sketchplugin file in the folder? Not sure how to install to sketch without it.
![Screen Shot 2019-06-07 at 11 54 46 AM](https://user-images.githubusercontent.com/17990837/59117124-11f67e80-891b-11e9-87b4-def52cd37921.png)

**Comment by rickmesser** [comment]
Hey, I can't find .sketchplugin file either! Is there any update to this?

**Comment by mathieudutour** [comment]
download it from the release page: https://github.com/mathieudutour/sketch-remove-bg/releases/latest/download/remove-bg.sketchplugin.zip
